#!/usr/bin/env python
from setuptools import setup, find_packages

setup_info = dict(
    name='CMI',
    version='0.1',
    author='E4R',
    author_email='e4r@thoughtworks.com',
    url='',
    download_url='',
    project_urls={
        'Documentation': '',
        'Source': '',
        'Tracker': '',
    },
    description='Cellular reprogramming framework',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    license='MIT',
    # Package info
    packages=['cmi'] + ['cmi.' + pkg for pkg in find_packages('cmi')],
    package_data={
        "cmi.tool.Signet": ["*.R", "*.txt"],
        "cmi.dependencies": ["transsynw/*/*", "SIGNET.py"]

    },
    # Add _ prefix to the names of temporary build dirs
    options={'build': {'build_base': '_build'}, },
    zip_safe=True,
    scripts=['bin/cmi'],
    install_requires=[
    'anndata==0.10.3',
    'array-api-compat==1.4',
    'backoff==2.2.1',
    'certifi==2023.11.17',
    'chardet==5.2.0',
    'charset-normalizer==3.3.2',
    'colorbrewer==0.2.0',
    'colour==0.1.5',
    'contourpy==1.2.0',
    'cycler==0.12.1',
    'decorator==5.1.1',
    'exceptiongroup==1.2.0',
    'filelock==3.13.1',
    'fonttools==4.47.0',
    'fsspec==2023.12.2',
    'get-annotations==0.1.2',
    'h5py==3.10.0',
    'idna==3.6',
    'igraph==0.10.8',
    'importlib-resources==6.1.1',
    'Jinja2==3.1.2',
    'joblib==1.3.2',
    'kiwisolver==1.4.5',
    'llvmlite==0.41.1',
    'louvain==0.8.1',
    'MarkupSafe==2.1.3',
    'matplotlib==3.8.2',
    'mpmath==1.3.0',
    'natsort==8.4.0',
    'networkx==3.2.1',
    'numba==0.58.1',
    'numpy==1.26.2',
    'packaging==23.2',
    'pandas==2.0.3',
    'patsy==0.5.5',
    'Pillow==10.1.0',
    'py4cytoscape==1.9.0',
    'pynndescent==0.5.11',
    'pyparsing==3.1.1',
    'python-dateutil==2.8.2',
    'pytz==2023.3.post1',
    'requests==2.31.0',
    'scanpy==1.9.6',
    'scikit-learn==1.3.2',
    'scipy==1.11.4',
    'seaborn==0.12.2',
    'session-info==1.0.0',
    'six==1.16.0',
    'statsmodels==0.14.1',
    'stdlib-list==0.10.0',
    'sympy==1.12',
    'texttable==1.7.0',
    'threadpoolctl==3.2.0',
    'torch==2.1.2',
    'tqdm==4.66.1',
    'typing_extensions==4.9.0',
    'tzdata==2023.3',
    'umap-learn==0.5.5',
    'urllib3==2.1.0',
    'zipp==3.17.0',
    'pandas==2.0.3',
    'scanpy==1.9.6',

    ]
)

setup(**setup_info)